# Generated by Django 5.2.6 on 2025-10-17 12:54

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Default discount percentage (0–100)', max_digits=5)),
                ('low_stock_threshold', models.IntegerField(default=10, help_text='Default low-stock threshold for medicines')),
                ('expired_date', models.TimeField(default=django.utils.timezone.now, help_text='Time of day to check for expired medicines')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
