# Generated by Django 5.2.6 on 2025-10-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Default discount percentage (0–100)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='expired_date',
            field=models.IntegerField(blank=True, default=30, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='low_stock_threshold',
            field=models.IntegerField(blank=True, default=10, help_text='Default low-stock threshold for medicines', null=True),
        ),
    ]
