# Generated by Django 5.2.5 on 2025-10-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_alter_setting_discount_alter_setting_expired_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='stock_carton',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='stock_unit',
            field=models.CharField(default='unit', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='units_per_carton',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='stock_in_unit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
