# Generated by Django 5.2.5 on 2025-10-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_medicine_stock_carton_medicine_stock_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='stock_in_carton',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='stock_unit',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='stock_in_unit',
            field=models.PositiveIntegerField(default=0, help_text='Loose units (e.g., bottles, strips).'),
        ),
    ]
