# Generated by Django 5.2.5 on 2025-10-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0005_remove_medicine_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='stock_unit',
            field=models.CharField(default='unit', max_length=50),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='stock_in_unit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
