# Generated by Django 5.2.5 on 2025-10-20 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_medicine_stock_unit_alter_medicine_stock_in_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='stock_unit',
        ),
    ]
