# Generated by Django 5.2.5 on 2025-10-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0007_remove_medicine_stock_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='sale_type',
            field=models.CharField(choices=[('unit', 'Unit'), ('carton', 'Carton')], default='unit', max_length=10),
        ),
    ]
