# Generated by Django 5.2.5 on 2025-10-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_saleitem_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='TIN_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
