# Generated by Django 5.2.5 on 2025-10-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0009_sale_tin_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='voucher_number',
            field=models.CharField(default=' ', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
