# Generated by Django 5.2.5 on 2025-10-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0010_sale_voucher_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='expired_date',
            field=models.IntegerField(default=30, help_text='Number of days before expiry to trigger near-expiry alerts.'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='low_threshold',
            field=models.IntegerField(default=10, help_text='Threshold to trigger low stock alerts (in units).'),
        ),
    ]
